from .aws import *

# FORCE_SCRIPT_NAME = ENV_TOKENS.get("FORCE_SCRIPT_NAME")

INSTALLED_APPS += ('wind','cvn_cms')
LMS_URL = ENV_TOKENS.get("LMS_URL")
LTI_LAUNCH_URL = ENV_TOKENS.get("LTI_LAUNCH_URL")
LTI_CONSUMER_KEY = ENV_TOKENS.get("LTI_CONSUMER_KEY")
LTI_CONSUMER_SECRET = ENV_TOKENS.get("LTI_CONSUMER_SECRET")

MITX_FEATURES['ENABLE_CREATOR_GROUP'] = True
